print("Enter first no.:")
num1=input()
print("Enter second no.:")
num2=input()
print(type(num1))
print(type(num2))
ans=int(num1)+int(num2)
print(type(num1))
print(type(num2))
print("Addition is:",ans)